// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRZKKu_oi-S4BnM4ccuIkwYFU3twvlsi0',
    appId: '1:1068003395602:web:93283878c8fa22e25f70cb',
    messagingSenderId: '1068003395602',
    projectId: 'app-fiestas-35a08',
    authDomain: 'app-fiestas-35a08.firebaseapp.com',
    storageBucket: 'app-fiestas-35a08.firebasestorage.app',
    measurementId: 'G-MMEFTWK86J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKGn2GXY_EXuOsktu4I4OMJL_H41qw570',
    appId: '1:1068003395602:android:1692ba61913a34195f70cb',
    messagingSenderId: '1068003395602',
    projectId: 'app-fiestas-35a08',
    storageBucket: 'app-fiestas-35a08.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4U-g2ST30XkkGtv6FSP1elDVJHmFlX6A',
    appId: '1:1068003395602:ios:bd9705b1357d52285f70cb',
    messagingSenderId: '1068003395602',
    projectId: 'app-fiestas-35a08',
    storageBucket: 'app-fiestas-35a08.firebasestorage.app',
    androidClientId: '1068003395602-4mi1ug0rheq98rfbee98i1652tcfp8bt.apps.googleusercontent.com',
    iosClientId: '1068003395602-3cuslehgd53h5m0fbvn7enafemphapph.apps.googleusercontent.com',
    iosBundleId: 'com.example.appFiestas',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4U-g2ST30XkkGtv6FSP1elDVJHmFlX6A',
    appId: '1:1068003395602:ios:bd9705b1357d52285f70cb',
    messagingSenderId: '1068003395602',
    projectId: 'app-fiestas-35a08',
    storageBucket: 'app-fiestas-35a08.firebasestorage.app',
    androidClientId: '1068003395602-4mi1ug0rheq98rfbee98i1652tcfp8bt.apps.googleusercontent.com',
    iosClientId: '1068003395602-3cuslehgd53h5m0fbvn7enafemphapph.apps.googleusercontent.com',
    iosBundleId: 'com.example.appFiestas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRZKKu_oi-S4BnM4ccuIkwYFU3twvlsi0',
    appId: '1:1068003395602:web:12537fd09f64ecd25f70cb',
    messagingSenderId: '1068003395602',
    projectId: 'app-fiestas-35a08',
    authDomain: 'app-fiestas-35a08.firebaseapp.com',
    storageBucket: 'app-fiestas-35a08.firebasestorage.app',
    measurementId: 'G-94EMHGE8F7',
  );
}
